import { test, expect } from '@playwright/test';
import { fileURLToPath } from 'url';

// Visual test for the Visual Diffs "compare font" mode (outline overlay).
// Fully offline: a small synthetic fixture font (tests/fixtures/test-font.ttf,
// generated by generate-font.mjs) is uploaded through the real file input, so
// this needs no network, no Local Font Access permission, and no Google Fonts.
const FIXTURE = fileURLToPath(new URL('./fixtures/test-font.ttf', import.meta.url));

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.clear());
  page.on('console', msg => { if (msg.type() === 'error') console.error('Browser error:', msg.text()); });
  page.on('pageerror', err => console.error('Page error:', err.message));
});

test('visualDiffs compare-font upload overlay', async ({ page }) => {
  // compare=font puts the tab in compare mode (Upload is the default source).
  await page.goto('?view=visualDiffs&compare=font&align=cap');

  // Use a short, deterministic string instead of the full character set.
  const textarea = page.locator('.input-wrapper textarea');
  await textarea.fill('Hagxo');

  // Upload the fixture font through the real <input type="file">.
  await page.locator('.font-compare-controls input[type="file"]').setInputFiles(FIXTURE);

  // The overlay SVG appears only once both the fixture font and Dactyl's
  // outlines are ready, so this also gates on generation completing.
  await page.waitForSelector('.svg-container svg', { timeout: 90_000 });

  await expect(page.locator('.preview-content')).toHaveScreenshot('visualDiffs-compare-upload.png');
});
