// Composite the Tweens tab's rows of tiny per-axis-value SVGs (already
// generated by the F# tweens API — see App.jsx's renderContent) into one
// standalone SVG document, mirroring the on-screen row layout. Pure string
// composition (nesting each variation's own already-complete <svg> inside a
// positioned <g>) — no DOM/canvas capture needed, so no risk of the
// foreignObject canvas-tainting issue splineGridSvg.js's comment documents.
//
// Each variation's <svg> has only a viewBox, no width/height (confirmed by
// hand) — nested inside another <svg> with no size of its own, that defaults
// to 100% of the *outer* canvas per the SVG spec, so every cell would render
// full-canvas-sized and stack on top of each other. A fixed width/height is
// injected onto each one's root tag before nesting, so its own
// viewBox/preserveAspectRatio scales it to fit a uniform cell size instead.
const CELL_SIZE = 110
const GAP = 12
const ROW_LABEL_H = 22
const ROW_GAP = 20
const VALUE_LABEL_H = 16
const PAD = 16

const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

const sizeSvg = (svg, size) => svg.replace(/^<svg /, `<svg width="${size}" height="${size}" `)

/// content: { [ctrlName]: [{ val, svg }] } — the tweens worker result.
/// controlDefinitions/tweenFilter/excludedAxes mirror the same filtering
/// renderContent applies for the on-screen grid, so the export matches what's
/// currently visible.
export function buildTweensSvg(content, controlDefinitions, tweenFilter, excludedAxes = ['spacing', 'leading']) {
    const rows = controlDefinitions
        .filter(c => !excludedAxes.includes(c.name) && c.category !== 'debug')
        .filter(c => !tweenFilter || c.name === tweenFilter)
        .map(ctrl => ({ ctrl, variations: content[ctrl.name] }))
        .filter(r => r.variations && r.variations.length)

    let y = PAD
    let maxW = 0
    const rowsSvg = rows.map(({ ctrl, variations }) => {
        let x = PAD
        const rowY0 = y
        const cells = variations.map((v) => {
            const label = ctrl.type_ === 'checkbox'
                ? (v.val === 'diff' ? 'diff' : v.val ? 'true' : 'false')
                : v.val.toFixed(2)
            const cell = `<g transform="translate(${x},${y + ROW_LABEL_H})">` +
                sizeSvg(v.svg, CELL_SIZE) +
                `<text x="0" y="${CELL_SIZE + VALUE_LABEL_H - 2}" font-size="11" fill="#333">${esc(label)}</text>` +
                `</g>`
            x += CELL_SIZE + GAP
            return cell
        })
        maxW = Math.max(maxW, x)
        const label = `<text x="${PAD}" y="${rowY0 + ROW_LABEL_H * 0.75}" font-size="14" font-weight="bold" fill="#111">${esc(ctrl.name)}</text>`
        y += ROW_LABEL_H + CELL_SIZE + VALUE_LABEL_H + ROW_GAP
        return label + cells.join('')
    })

    const totalW = maxW + PAD
    const totalH = y
    return `<svg xmlns="http://www.w3.org/2000/svg" width="${totalW}" height="${totalH}" viewBox="0 0 ${totalW} ${totalH}">` +
        `<rect width="${totalW}" height="${totalH}" fill="#ffffff"/>` +
        rowsSvg.join('') +
        `</svg>`
}
